networks:
  user-network:
    driver: bridge
    name: user-network
  nginx-network:
    driver: bridge
    name: nginx-network

services:
  db:
    image: postgres
    container_name: psql-user
    # restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./postgres_data_user:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}" ]
      interval: 20s
      timeout: 5s
      retries: 5
    networks:
      - user-network
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: artform-user-server
    container_name: artform-user-server
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${SERVER_PORT}:8081"
    environment:
      - SERVER_DOMAIN=${SERVER_DOMAIN}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${PSQL_USERNAME}
      - DB_PASSWORD=${PSQL_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - user-network
      - nginx-network
    restart: always
