scrape_configs:
  - job_name: 'artform-core-server'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['artform-core-server:1111']
  
  - job_name: 'artform-user-server'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['artform-user-server:1111']