spring:
  application:
    name: artform-core

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create

  datasource:
    hikari:
      maximum-pool-size: 4
    url: jdbc:postgresql://${SERVER_DOMAIN}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

# S3 설정
cloud:
  aws:
    s3:
      bucket: ${BUCKET_NAME}
    credentials:
      access-key: ${ACCESS_KEY_ID}
      secret-key: ${SECRET_ACCESS_KEY}
    region:
      static: ap-northeast-2
    stack:
      auto: false

# 로그 설정
logging:
  level:
    com.d103.artformcore: DEBUG