spring:
  application:
    name: artform-core

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create

  datasource:
    hikari:
      maximum-pool-size: 4
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
#    driver-class-name: org.postgresql.Driver

# 로그 설정

# S3 설정
cloud:
  aws:
    s3:
      bucket: ${BUCKET_NAME}
    credentials:
      access-key: ${ACCESS_KEY_ID}
      secret-key: ${SECRET_ACCESS_KEY}
    region:
      static: ap-northeast-2
    stack:
      auto: false

logging:
  level:
    com.d103.artformcore: DEBUG