services:
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf.d:/etc/nginx/conf.d
      - letsencrypt_certs:/etc/letsencrypt
      - letsencrypt_data:/var/lib/letsencrypt
    networks:
      - nginx-network
    restart: always

volumes:
  letsencrypt_certs:
    external: true
  letsencrypt_data:
    external: true

networks:
  nginx-network:
    external: true
