services:
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - letsencrypt_certs:/etc/letsencrypt:ro
      - letsencrypt_data:/var/lib/letsencrypt
    restart: always

  certbot:
    image: certbot/certbot
    volumes:
      - letsencrypt_certs:/etc/letsencrypt
      - letsencrypt_data:/var/lib/letsencrypt
      - webroot:/var/www/html
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --webroot --webroot-path=/var/www/html; sleep 12h & wait $${!}; done;'" # 인증서 자동 갱신
    restart: always

volumes:
  letsencrypt_certs:
    external: true
  letsencrypt_data:
    external: true
  webroot:

networks:
  nginx-network:
    external: true
