spring:
  application:
    name: artform

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create

  datasource:
    hikari:
      maximum-pool-size: 4
    url: jdbc:postgresql://${DB_URL}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
