networks:
  core-network:
    driver: bridge
    name: core-network
  nginx-network:
    driver: bridge
    name: nginx-network

services:
  db:
    image: postgres
    container_name: psql-core
    # restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./postgres_data_core:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}" ]
      interval: 20s
      timeout: 5s
      retries: 5
    networks:
      - core-network
  app:
    build: 
      context: ./
      dockerfile: Dockerfile
    image: artform-core-server
    container_name: artform-core-server
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${SERVER_PORT}:8081"
    environment:
      - SERVER_DOMAIN=${SERVER_DOMAIN}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${PSQL_USERNAME}
      - DB_PASSWORD=${PSQL_PASSWORD}
      - BUCKET_NAME=${BUCKET_NAME}
      - ACCESS_KEY_ID=${ACCESS_KEY_ID}
      - SECRET_ACCESS_KEY=${SECRET_ACCESS_KEY}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - core-network
      - nginx-network
    restart: always

 # test
